/**
 * Ratings API Route
 * 
 * Handles all rating-related operations:
 * - GET: Fetch all ratings for a user
 * - POST: Create a new rating
 * - DELETE: Remove a rating (we'll add later)
 * 
 * URL: /api/ratings
 */

import { NextRequest, NextResponse } from 'next/server'
import { supabase } from '@/lib/supabase'

/**
 * GET /api/ratings
 * 
 * Fetches all ratings for a specific user
 * 
 * Query Parameters:
 * - user_id: UUID of the user (required)
 * 
 * Example: /api/ratings?user_id=abc-123
 * 
 * Returns: Array of ratings
 */
export async function GET(request: NextRequest) {
  try {
    // Extract query parameters from URL
    // searchParams is like a dictionary of ?key=value pairs
    const searchParams = request.nextUrl.searchParams
    const userId = searchParams.get('user_id')

    // Validation: Make sure user_id was provided
    if (!userId) {
      return NextResponse.json(
        { 
          success: false, 
          error: 'user_id is required' 
        },
        { status: 400 }  // 400 = Bad Request
      )
    }

    /**
     * Query database using Supabase
     * 
     * .from('ratings') - Select the ratings table
     * .select('*') - Get all columns
     * .eq('user_id', userId) - Where user_id equals our userId
     * .order('timestamp', { ascending: false }) - Newest first
     */
    const { data, error } = await supabase
      .from('ratings')
      .select('*')
      .eq('user_id', userId)
      .order('timestamp', { ascending: false })

    // Check if query failed
    if (error) {
      console.error('Database error:', error)
      return NextResponse.json(
        { 
          success: false, 
          error: 'Failed to fetch ratings' 
        },
        { status: 500 }  // 500 = Internal Server Error
      )
    }

    // Success! Return the data
    return NextResponse.json({
      success: true,
      data: data || []  // Return empty array if no data
    })

  } catch (error) {
    // Catch any unexpected errors
    console.error('Unexpected error:', error)
    return NextResponse.json(
      { 
        success: false, 
        error: 'Internal server error' 
      },
      { status: 500 }
    )
  }
}

/**
 * POST /api/ratings
 * 
 * Creates a new rating in the database
 * 
 * Request Body (JSON):
 * {
 *   "user_id": "abc-123",
 *   "show_name": "Stranger Things",
 *   "episode_number": "S4E9",
 *   "episode_title": "The Piggyback",
 *   "rating": 9,
 *   "platform": "Netflix",
 *   "genre": "Sci-Fi",
 *   "url": "https://netflix.com/..."
 * }
 * 
 * Returns: The created rating with generated ID
 */
export async function POST(request: NextRequest) {
  try {
    // Parse JSON body from request
    // request.json() converts JSON string to JavaScript object
    const body = await request.json()

    // Destructure the fields we need
    const {
      user_id,
      show_name,
      episode_number,
      episode_title,
      rating,
      platform,
      genre,
      url
    } = body

    // Validation: Check required fields
    if (!user_id || !show_name || !rating) {
      return NextResponse.json(
        { 
          success: false, 
          error: 'user_id, show_name, and rating are required' 
        },
        { status: 400 }
      )
    }

    // Validation: Check rating is between 1-10
    if (rating < 1 || rating > 10) {
      return NextResponse.json(
        { 
          success: false, 
          error: 'rating must be between 1 and 10' 
        },
        { status: 400 }
      )
    }

    /**
     * Insert new rating into database
     * 
     * .insert() - Create new row
     * .select() - Return the created row
     * .single() - Expect only one row back
     * 
     * Note: timestamp is auto-generated by database (DEFAULT now())
     */
    const { data, error } = await supabase
      .from('ratings')
      .insert({
        user_id,
        show_name,
        episode_number: episode_number || null,
        episode_title: episode_title || null,
        rating,
        platform: platform || 'Netflix',
        genre: genre || null,
        url: url || null,
        // timestamp is automatic (DEFAULT now() in SQL)
      })
      .select()
      .single()

    // Check if insert failed
    if (error) {
      console.error('Database error:', error)
      return NextResponse.json(
        { 
          success: false, 
          error: 'Failed to create rating' 
        },
        { status: 500 }
      )
    }

    // Success! Return the created rating
    return NextResponse.json(
      {
        success: true,
        data
      },
      { status: 201 }  // 201 = Created
    )

  } catch (error) {
    console.error('Unexpected error:', error)
    return NextResponse.json(
      { 
        success: false, 
        error: 'Internal server error' 
      },
      { status: 500 }
    )
  }
}